apiVersion: v1
data:
  compras.html: |
    Este es el archivo de compras


    Aca esta todas las compras que siempre necesitaste.

    Saludos coordiales.
  index.html: |
    Este es el archivo de compras
    Que no deberia existir mas...


    Aca esta todas las compras que siempre necesitaste.

    Saludos coordiales.
kind: ConfigMap
metadata:
  name: compras-config-1
  namespace: compras
  labels:
    syntax-checking: "true"
    config-type: file
